---
- name: Install nginx
  become: true
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  become: true
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  become: true
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: http service state
  become: true
  service: name=nginx state=started enabled=yes
