heat_template_version: 2015-10-15

description: A Group of Load Balanced Servers

parameters:
  web1_ip:
    type: string
    description: IP used by web-1 server
  web2_ip:
    type: string
    description: IP used by web-1 server
  app_port:
    type: number
    default: 80
    description: Port used by the servers
  lb_port:
    type: number
    default: 80
    description: Port used by the load balancer
  subnet:
    type: string
    description: Subnet for the load balancer
  public_network:
    type: string
    description: Network used by the load balancer

resources:
  pool_member1:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_param: web1_ip}
      protocol_port: { get_param: app_port }
      subnet: { get_param: subnet }

  pool_member2:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_param: web2_ip}
      protocol_port: { get_param: app_port }
      subnet: { get_param: subnet }

  monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      delay: 3
      type: TCP
      timeout: 3
      max_retries: 3
      pool: { get_resource: pool }

  pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      listener: { get_resource: listener }

  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: loadbalancer }
      protocol: HTTP
      protocol_port: { get_param: lb_port }

  loadbalancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: { get_param: subnet }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_attr: [loadbalancer, vip_port_id ]}

outputs:
  lburl:
    value:
      str_replace:
        template: http://IP_ADDRESS
        params:
          IP_ADDRESS: { get_attr: [ floating_ip, floating_ip_address ] }
    description: >
      This URL is the "external" URL that can be used to access the
      load balancer.
